# Generated by Django 5.0.4 on 2024-08-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='image_url',
            field=models.URLField(max_length=10000),
        ),
    ]
